name: deploy

on:
#  workflow_run:
#    workflows:
#      - ./.github/workflows/go.yml
#    types:
#      - completed
#    branches: [ "*" ]
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: dummy
        run: echo deploying
