name: deploy

on:
  workflow_run:
    workflows:
      - project1
    types:
      - completed
    branches: [ "*" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: dummy
        run: echo deploying
