name: e2e-project2

on:
  push:
    branches: ["main"]
    paths:
      - src/tests/e2e/project2/**
  pull_request:
    branches: ["main"]
    paths:
      - src/tests/e2e/project2/**

jobs:
  e2e:
    uses: ./.github/workflows/e2e-project.yml
    with:
      path: src/tests/e2e/project2
      is_service_call: false
