name: go

on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string
  push:
    branches: [ "main" ]
    paths:
      - ${{ inputs.directory }}/**
    pull_request:
      branches: [ "main" ]
      paths:
        - ${{ inputs.directory }}/**


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        working-directory: ${{ inputs.directory }}
        run:  |
          go build -v ./...

      - name: Test
        working-directory: ${{ inputs.directory }}
        run: |
          go test -v ./...