name: project2

on:
  push:
    branches: ["main"]
    paths:
      - src/services/project2/**
  pull_request:
    branches: ["main"]
    paths:
      - src/services/project2/**

jobs:
  go_workflow:
    uses: ./.github/workflows/go.yml
    with:
      directory: src/services/project2
  e2e_project2:
    uses: ./.github/workflows/e2e-project.yml
    with:
      path: src/tests/e2e/project2
      is_service_call: true
  sleep:
    runs-on: ubuntu-latest
    steps:
      - name: sleep
        run: sleep 10
    needs:
      - go_workflow
