name: project2

on:
  push:
    branches: [ "main" ]
    paths:
      - project1/**
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: project2

jobs:
  go_workflow:
    uses: ./.github/workflows/go.yml



