name: project3

on:
  push:
    branches: [ "main" ]
    paths:
      - project/**
  pull_request:
    branches: [ "main" ]
    paths:
      - project2/**

jobs:
  go_workflow:
    uses: ./.github/workflows/go.yml
    with:
      directory: project2
  sleep:
    runs-on: ubuntu-latest
    steps:
      - name: sleep
        run: sleep 60
    needs:
      - go_workflow


