name: project1

on:
  push:
    branches: [ "main" ]
    paths:
      - project1/**
  pull_request:
    branches: [ "main" ]

jobs:
  go_workflow:
    uses: ./.github/workflows/go.yml
    with:
      directory: project1