name: project2

on:
  push:
    branches: [ "main" ]
    paths:
      - project2/**
  pull_request:
    branches: [ "main" ]
    paths:
      - project2/**

jobs:
  go_workflow:
    uses: ./.github/workflows/go.yml
    with:
      directory: project2


