name: wait-deploy

on:
  pull_request:
    branches: ["main"]
    paths:
      - src/services/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Pause until all workflows are completed
        uses: willgarcia/workflow-wait-action@2d07bb061039e4b7705e303f734963a9cf93a092
        with:
          workflows: |
            go_workflow

      - name: dummy
        run: |
          echo deploying
          date
