name: wait-deploy

on:
  workflow_run:
    workflows:
      - project1
      - project2
    types:
      - completed
    branches:
      - "*"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: dummy
        run: echo deploying
